"""empty message

Revision ID: 8564442f6f8e
Revises: 
Create Date: 2020-09-10 16:54:03.191749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8564442f6f8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wave_height', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tide', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('wind', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('swells', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weather', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('h20_temp', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='report_pkey')
    )
    # ### end Alembic commands ###
